### ISSUE TITLE
Stack-Auth SaaS creates duplicated accounts for same email

### ISSUE THREAD

**Issue by KemingHe** [stack-auth/stack#379]
## Problem

Both my Google and GitHub accounts use the public `keminghe.career[at]gmail.com` email. 

I first signed into [`app.stack-auth.com`](https://app.stack-auth.com) using the **Google Sign-in** option and created my projects fine.

One day, I clicked on the **GitHub Sign-in** option and noticed that instead of linking me to my Google Sign-in account with the same email, a **new** account was created for me with no projects. 

## Expected Behavior

Per best practice, no matter which OAuth provider, one email should correspond to one account. 

## How to Reproduce

1. Use a Gmail for your GitHub account.
2. Sign in to the Stack SaaS first using Google Sign-in, create a basic project.
3. Sign out from the Stack SaaS.
4. Next sign in using the GitHub Sign-in option, and see that the project you just created is not there, implying a new account has been created.

## Proposed Solution

Add account/email linking feature for OAuth sign-in options, check if user with email already exists and has their account init with another provider.

This will make a great feature for self-hosted devs as well.

**Comment by fomalhautb** [comment]
This is not a bug, but it is an expected behavior seen on many websites like Posthog, Sentry, ChatGPT, and Vercel. There are two main reasons:
1. Merging accounts with the same email isn't always feasible, as providers like Facebook and Twitter don't confirm if an email is verified. Merging unverified emails can risk account takeovers.
2. For B2B use cases, OAuth accounts are typically organization-owned. If access to an OAuth account is revoked, the user shouldn’t still be able to log in. Allowing account merging would undermine this.

That said, we understand that for B2C scenarios or when emails are verified, auto-merging might be preferred to avoid creating duplicate accounts. We do have plans to add an option for auto-merging when possible.
